package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.55

import (
	"context"
	"fmt"

	"github.com/Jason2924/st-enginerring_test/graph/model"

	"github.com/Jason2924/st-enginerring_test/entities"
)

// CreateProduct is the resolver for the createProduct field.
func (r *mutationResolver) CreateProduct(ctx context.Context, input model.NewProduct) (*model.Product, error) {
	panic(fmt.Errorf("not implemented: CreateProduct - createProduct"))
}

// Products is the resolver for the products field.
func (r *queryResolver) Products(ctx context.Context, limit int, page int) ([]*model.Product, error) {
	reqt := &entities.ProductListManyReqt{
		Limit: limit,
		Page:  page,
	}
	return r.ProductService.ListMany(ctx, reqt)
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
